Repository opendatahub-io/caikit-tgis-serving, pull requests merged in 2023-08, with the labels that each got.

#37 Update Kserve.md
  demo/kserve/Kserve.md
Labels: approved, lgtm, needs-ok-to-test

#38 restucture metrics instructions
  demo/kserve/Kserve.md
  demo/kserve/custom-manifests/service-mesh/peer-authentication-test-ns.yaml
Labels: approved, lgtm

#40 Update README.md
  docs/README.md
Labels: approved, lgtm, needs-ok-to-test

#34 Unit tests
  Dockerfile
  Makefile
  test/smoke-test.sh
Labels: approved

#42 Merge stable fixes to release branch
  Dockerfile
  Makefile
  caikit/Pipfile
  caikit/Pipfile.lock
  caikit/config/caikit-tgis.template.yml
  docs/README.md
  test/smoke-test.sh
Labels: approved

#43 Update makefile to remove DTYPE_STR as it's no longer needed
  Makefile
  demo/kserve/custom-manifests/caikit/caikit-servingruntime.yaml
Labels: approved, lgtm

#44 remove oc apply for namespaced SMMR
  demo/kserve/Kserve.md
Labels: approved, lgtm

#46 add instructions according to metrics controller
  demo/kserve/Kserve.md
  demo/kserve/custom-manifests/metrics/kserve-prometheus-k8s.yaml
  demo/kserve/custom-manifests/opendatahub/kfdef-odh-model-controller.yaml
  demo/kserve/custom-manifests/service-mesh/istio-proxies-monitor.yaml
  demo/kserve/custom-manifests/service-mesh/istiod-monitor.yaml
  demo/kserve/custom-manifests/service-mesh/smcp.yaml
Labels: approved, lgtm

#48 Remove kfdef for monitoring
  demo/kserve/Kserve.md
Labels: approved, lgtm

#50 Dep update, security fixes
  Dockerfile
  Makefile
  caikit/Pipfile.lock
Labels: approved, lgtm

#53 replace sleep cmd of a watching logic to wait for pod ready
  demo/kserve/scripts/install/kserve-install.sh
  demo/kserve/scripts/test/grpc-call.sh
  demo/kserve/scripts/uninstall/dependencies-uninstall.sh
  demo/kserve/scripts/uninstall/kserve-uninstall.sh
  demo/kserve/scripts/utils.sh
Labels: approved

#54 Enhance scripts and support long CN using SAN
  demo/kserve/scripts/generate-wildcard-certs.sh
  demo/kserve/scripts/install/kserve-install.sh
  demo/kserve/scripts/test/delete-model.sh
  demo/kserve/scripts/test/deploy-model.sh
  demo/kserve/scripts/test/grpc-call.sh
  demo/kserve/scripts/uninstall/dependencies-uninstall.sh
  demo/kserve/scripts/uninstall/kserve-uninstall.sh
  demo/kserve/scripts/utils.sh
Labels: approved

#55 update check logic for BREW environment variable
  demo/kserve/scripts/install/kserve-install.sh
Labels: approved

#56 Update to use micropipenv
  Dockerfile
Labels: approved, lgtm

#51 added safety measures to cleanup script.
  demo/kserve/scripts/uninstall/dependencies-uninstall.sh
Labels: approved, lgtm, needs-rebase

#57 add a parameter for custom manifests url
  demo/kserve/scripts/README.md
  demo/kserve/scripts/install/kserve-install.sh
Labels: approved

#62 fix checking if env variable exist
  demo/kserve/scripts/install/kserve-install.sh
  demo/kserve/scripts/uninstall/dependencies-uninstall.sh
  demo/kserve/scripts/uninstall/kserve-uninstall.sh
Labels: approved

#61 Issue #58: Update and Restructure Quickstart
  demo/kserve/KServe_Authorino.md
  demo/kserve/Kserve.md
  demo/kserve/README.md
  demo/kserve/create-minio.md
  demo/kserve/custom-manifests/metrics/uwm-cm-conf.yaml
  demo/kserve/custom-manifests/metrics/uwm-cm-enable.yaml
  demo/kserve/deploy-remove.md
  demo/kserve/install-manual.md
  demo/kserve/metrics.md
  demo/kserve/scripts/README.md
  demo/kserve/traffic-splitting.md
  demo/kserve/upgrade-runtime.md
  docs/README.md
Labels: approved, lgtm

#63 addressing comments from PR 61
  demo/kserve/custom-manifests/minio/minio-secret.yaml
  demo/kserve/custom-manifests/minio/minio.yaml
  demo/kserve/deploy-remove.md
  demo/kserve/install-manual.md
  docs/README.md
Labels: approved, lgtm
