Repository opendatahub-io/caikit-tgis-serving, pull requests merged in 2023-11, with the labels that each got.

#127 remove ns variable
  demo/kserve/metrics.md
Labels: approved, lgtm

#122 Add console file for demo/kserve/scripts/test
  demo/kserve/scripts/test/grpc-console.sh
Labels: lgtm, needs-ok-to-test

#132 Add TGIS Standalone SR and ISVC
  demo/kserve/custom-manifests/caikit/tgis-isvc.yaml
  demo/kserve/custom-manifests/caikit/tgis-servingruntime.yaml
Labels: approved, lgtm

#131 Put caikit's base config back into the container
  Dockerfile
  caikit.yml
  demo/kserve/custom-manifests/caikit/caikit-servingruntime.yaml
  demo/kserve/custom-manifests/caikit/caikit-tgis-isvc.yaml
  demo/kserve/custom-manifests/caikit/caikit-tgis-servingruntime-template.yaml
  demo/kserve/custom-manifests/caikit/caikit-tgis-servingruntime.yaml
  demo/kserve/deploy-remove.md
  demo/kserve/performance-config.md
  demo/kserve/scripts/test/deploy-model.sh
  docs/caikit-isvc.yaml
  docs/caikit-servingruntime.yaml
Labels: approved

#145 Prevent dependencies uninstall script from breaking RHODS
  demo/kserve/scripts/install/2-required-crs.sh
Labels: lgtm, needs-ok-to-test
