Repository opendatahub-io/caikit-tgis-serving, pull requests merged in 2023-10, with the labels that each got.

#85 Update caikit-nlp to 6f09931
  Dockerfile
  Makefile
  caikit/Pipfile
  caikit/Pipfile.lock
Labels: approved, lgtm

#97 auto add new issues to odh boards
  .github/workflows/auto-add-issues-to-project.yaml
Labels: approved, lgtm

#100 Update Caikit load_timeout to 3600s for TGIS backend
  caikit/config/caikit-tgis.template.yml
Labels: approved

#102 Re-add TGIS update
  Dockerfile
  Makefile
  caikit/Pipfile
  caikit/Pipfile.lock
Labels: approved

#101 1.34 merge to release
  Dockerfile
  Makefile
  caikit/Pipfile
  caikit/Pipfile.lock
  caikit/config/caikit-tgis.template.yml
  demo/kserve/built-tip.md
  demo/kserve/custom-manifests/caikit/caikit-servingruntime-template.yaml
  demo/kserve/custom-manifests/caikit/caikit-servingruntime.yaml
  demo/kserve/custom-manifests/opendatahub/brew-operators-2.x.yaml
  demo/kserve/custom-manifests/opendatahub/kserve-dsc-v1alpha1.yaml
  demo/kserve/custom-manifests/opendatahub/kserve-dsc.yaml
  demo/kserve/custom-manifests/opendatahub/odh-operators-2.x.yaml
  demo/kserve/custom-manifests/opendatahub/rhods-operators-2.x.yaml
  demo/kserve/deploy-remove.md
  demo/kserve/install-manual.md
  demo/kserve/performance-config.md
  demo/kserve/scripts/README.md
  demo/kserve/scripts/env.sh
  demo/kserve/scripts/install/kserve-install.sh
  demo/kserve/scripts/uninstall/kserve-uninstall.sh
  docs/README.md
Labels: approved

#105 correct COMMON_NAME generation
  demo/kserve/install-manual.md
Labels: approved, lgtm

#103 Update grpc_health_probe
  Dockerfile
Labels: approved, lgtm, ok-to-test

#106 update scripts/doc for mtls=true, refactorying sript structure
  demo/kserve/custom-manifests/opendatahub/kserve-dsc-v1alpha1.yaml
  demo/kserve/custom-manifests/serverless/gateways.yaml
  demo/kserve/custom-manifests/service-mesh/default-smmr.yaml
  demo/kserve/custom-manifests/service-mesh/operators.yaml
  demo/kserve/custom-manifests/service-mesh/peer-authentication-odh.yaml
  demo/kserve/custom-manifests/service-mesh/peer-authentication-rhods.yaml
  demo/kserve/custom-manifests/service-mesh/peer-authentication-test-ns.yaml
  demo/kserve/custom-manifests/service-mesh/peer-authentication.yaml
  demo/kserve/custom-manifests/service-mesh/smcp.yaml
  demo/kserve/custom-manifests/service-mesh/smmr-odh.yaml
  demo/kserve/deploy-remove.md
  demo/kserve/install-manual.md
  demo/kserve/scripts/README.md
  demo/kserve/scripts/env.sh
  demo/kserve/scripts/install/1-prerequisite-operators.sh
  demo/kserve/scripts/install/2-required-crs.sh
  demo/kserve/scripts/install/3-only-kserve-install.sh
  demo/kserve/scripts/install/check-env-variables.sh
  demo/kserve/scripts/install/kserve-install.sh
  demo/kserve/scripts/install/workaround.sh
  demo/kserve/scripts/test/delete-model.sh
  demo/kserve/scripts/test/deploy-model.sh
  demo/kserve/scripts/uninstall/dependencies-uninstall.sh
  demo/kserve/scripts/uninstall/kserve-uninstall.sh
  demo/kserve/scripts/utils.sh
Labels: approved, lgtm

#107 Split caikit-tgis into separate containers
  .dockerignore
  .gitattributes
  Dockerfile
  Makefile
  caikit/Pipfile
  caikit/Pipfile.lock
  caikit/config/caikit-tgis.template.yml
  caikit/start-serving.sh
  demo/kserve/built-tip.md
  docs/caikit-isvc.yaml
  docs/caikit-servingruntime.yaml
  poetry.lock
  pyproject.toml
  test/smoke-test.sh
Labels: approved, lgtm

#112 Add caikit+tgis smoke test
  test/.gitignore
  test/caikit_config/caikit.yml
  test/docker-compose.yml
  test/smoke-test.sh
Labels: lgtm

#117 deps: run poetry update
  poetry.lock
Labels: approved, lgtm, dependencies

#123 Add GitHub actions smoke test
  .github/workflows/smoke-test.yml
  test/docker-compose.yml
  test/smoke-test.sh
Labels: approved, lgtm

#118 Add dependabot config
  .github/dependabot.yml
Labels: approved, lgtm
