Repository opendatahub-io/caikit-tgis-serving, pull requests merged in 2023-07, with the labels that each got.

#4 Clean up repo structure, add pipfile and makefile
  Dockerfile
  Makefile
  caikit/Pipfile
  caikit/Pipfile.lock
  caikit/config/caikit-tgis.template.yml
  caikit/start-serving.sh
  docs/README.md
  docs/caikit-isvc.yaml
  docs/caikit-servingruntime.yaml
  utils/convert.py
Labels: approved, lgtm

#8 Update dockerfile to working TGIS image
  Dockerfile
Labels: approved, lgtm

#10 add gitaction to delete pr image from quay.io
  .github/workflows/pr-close-image-delete.yaml
Labels: approved

#9 Update to ensure caikit user is 1001 in image
  Dockerfile
Labels: approved, lgtm

#15 Fix gitaction secrets
  .github/workflows/pr-close-image-delete.yaml
Labels: approved

#17 update gitaction event
  .github/workflows/pr-close-image-delete.yaml
Labels: approved

#16 Upload a demo for KServe with Caikit + TGIS runtime
  demo/kserve/.gitignore
  demo/kserve/KServe_Authorino.md
  demo/kserve/Kserve.md
  demo/kserve/OSSM-enabled.md
  demo/kserve/README.md
  demo/kserve/custom-manifests/authorino/operators.yaml
  demo/kserve/custom-manifests/caikit/caikit-isvc.yaml
  demo/kserve/custom-manifests/caikit/caikit-servingruntime.yaml
  demo/kserve/custom-manifests/minio/minio-secret.yaml
  demo/kserve/custom-manifests/minio/minio.yaml
  demo/kserve/custom-manifests/minio/serviceaccount-minio.yaml
  demo/kserve/custom-manifests/opendatahub/kfdef-kserve-op.yaml
  demo/kserve/custom-manifests/opendatahub/kfdef-kserve.yaml
  demo/kserve/custom-manifests/opendatahub/kfdef-no-plugins.yaml
  demo/kserve/custom-manifests/opendatahub/kfdef-plugins.yaml
  demo/kserve/custom-manifests/opendatahub/operators.yaml
  demo/kserve/custom-manifests/serverless/gateways.yaml
  demo/kserve/custom-manifests/serverless/operators.yaml
  demo/kserve/custom-manifests/service-mesh/operators.yaml
  demo/kserve/custom-manifests/service-mesh/peer-authentication.yaml
  demo/kserve/custom-manifests/service-mesh/smcp.yaml
  demo/kserve/custom-manifests/service-mesh/smmr.yaml
  demo/kserve/scripts/generate-wildcard-certs.sh
Labels: approved

#19 Add user home to caikit user, update dockerfile for yum clean, update example servingruntime
  Dockerfile
  docs/caikit-servingruntime.yaml
Labels: approved, lgtm

#21 Fix types in demo
  demo/kserve/README.md
Labels: approved

#29 Add instructions to enable metrics for caikit tgis
  demo/kserve/Kserve.md
  demo/kserve/custom-manifests/caikit/caikit-servingruntime.yaml
  demo/kserve/custom-manifests/metrics/caikit-metrics-service.yaml
  demo/kserve/custom-manifests/metrics/caikit-metrics-servicemonitor.yaml
  demo/kserve/custom-manifests/metrics/networkpolicy-uwm.yaml
  demo/kserve/custom-manifests/metrics/peerauthentication-caikit-metrics.yaml
Labels: approved, lgtm

#30 allow custom namespace for metrics resources
  demo/kserve/Kserve.md
  demo/kserve/custom-manifests/metrics/caikit-metrics-service.yaml
  demo/kserve/custom-manifests/metrics/caikit-metrics-servicemonitor.yaml
  demo/kserve/custom-manifests/metrics/peerauthentication-caikit-metrics.yaml
Labels: approved, lgtm

#32 Fix small parts for Kserve doc
  demo/kserve/Kserve.md
  demo/kserve/custom-manifests/minio/minio.yaml
  demo/kserve/custom-manifests/service-mesh/smmr.yaml
Labels: approved, odh-release/1.8

#35 Add missing NS flags and minor changes to the kserve demo
  demo/kserve/Kserve.md
  demo/kserve/custom-manifests/minio/serviceaccount-minio.yaml
Labels: needs-ok-to-test
