Repository opendatahub-io/caikit-tgis-serving, pull requests merged in 2023-09, with the labels that each got.

#65 caikit-tgis-serving quickstart edit
  demo/kserve/create-minio.md
  demo/kserve/deploy-remove-scripts.md
  demo/kserve/deploy-remove.md
  demo/kserve/install-manual.md
  demo/kserve/metrics.md
  demo/kserve/scripts/README.md
  docs/README.md
Labels: approved, lgtm, needs-ok-to-test

#69 [Sync] Update Release branch based on main
  Dockerfile
  demo/kserve/KServe_Authorino.md
  demo/kserve/Kserve.md
  demo/kserve/README.md
  demo/kserve/create-minio.md
  demo/kserve/custom-manifests/metrics/uwm-cm-conf.yaml
  demo/kserve/custom-manifests/metrics/uwm-cm-enable.yaml
  demo/kserve/custom-manifests/minio/minio-secret.yaml
  demo/kserve/custom-manifests/minio/minio.yaml
  demo/kserve/deploy-remove-scripts.md
  demo/kserve/deploy-remove.md
  demo/kserve/install-manual.md
  demo/kserve/metrics.md
  demo/kserve/scripts/README.md
  demo/kserve/scripts/generate-wildcard-certs.sh
  demo/kserve/scripts/install/kserve-install.sh
  demo/kserve/scripts/test/delete-model.sh
  demo/kserve/scripts/test/deploy-model.sh
  demo/kserve/scripts/test/grpc-call.sh
  demo/kserve/scripts/uninstall/dependencies-uninstall.sh
  demo/kserve/scripts/uninstall/kserve-uninstall.sh
  demo/kserve/scripts/utils.sh
  demo/kserve/traffic-splitting.md
  demo/kserve/upgrade-runtime.md
  docs/README.md
Labels: approved, lgtm

#68 update caikit-nlp package version
  Dockerfile
  caikit/Pipfile
Labels: approved, lgtm

#78 fix ISSUE-70
  demo/kserve/scripts/README.md
Labels: approved, lgtm

#77 update scripts and docs for kserve
  demo/kserve/custom-manifests/caikit/caikit-servingruntime-template.yaml
  demo/kserve/custom-manifests/caikit/caikit-servingruntime.yaml
  demo/kserve/custom-manifests/opendatahub/brew-operators-2.x.yaml
  demo/kserve/custom-manifests/opendatahub/kserve-dsc.yaml
  demo/kserve/custom-manifests/opendatahub/odh-operators-2.x.yaml
  demo/kserve/custom-manifests/opendatahub/rhods-operators-2.x.yaml
  demo/kserve/install-manual.md
  demo/kserve/scripts/install/kserve-install.sh
  demo/kserve/scripts/uninstall/kserve-uninstall.sh
Labels: approved, lgtm

#79 Add initial performance tuning docs
  demo/kserve/performance-config.md
  docs/README.md
Labels: kind/documentation, approved, lgtm

#76 add grpc_health_probe binary for the use-cases without kserve
  Dockerfile
Labels: approved, lgtm

#80 Modified the missing steps
  demo/kserve/deploy-remove.md
Labels: approved, lgtm, needs-ok-to-test

#82 Fix catalogsource for rhods
  demo/kserve/custom-manifests/opendatahub/rhods-operators-2.x.yaml
Labels: approved, lgtm

#84 update scripts to support odh
  demo/kserve/custom-manifests/opendatahub/kserve-dsc-v1alpha1.yaml
  demo/kserve/custom-manifests/opendatahub/kserve-dsc.yaml
  demo/kserve/scripts/env.sh
  demo/kserve/scripts/install/kserve-install.sh
  demo/kserve/scripts/uninstall/kserve-uninstall.sh
Labels: approved, lgtm

#86 Update model conversion instructions
  demo/kserve/built-tip.md
Labels: approved, lgtm
