Repository opendatahub-io/caikit-tgis-serving, pull requests merged in 2024-08, with the labels that each got.

#342 Update NLTK to patch CVE-2024-39705
  poetry.lock
Labels: approved

#346 deps: bump nltk to 3.9.1
  poetry.lock
Labels: approved, ok-to-test

#349 docker compose v2 migration
  test/compose/smoke-test.sh
  test/smoke-test.py
Labels: approved

#351 gha: bump kserve version in kserve test worfklow
  .github/workflows/kserve-test.yml
Labels: approved

#352 deps: bump caikit,caikit-tgis-backend, run poetry update
  poetry.lock
  pyproject.toml
Labels: approved

#355 Sync Release to main branch for 2.13
  .github/workflows/kserve-test.yml
  poetry.lock
  pyproject.toml
  test/compose/smoke-test.sh
  test/smoke-test.py
Labels: approved, lgtm
