Repository opendatahub-io/caikit-tgis-serving, pull requests merged in 2024-07, with the labels that each got.

#324 bump dependencies
  poetry.lock
  pyproject.toml
Labels: approved

#332 Sync release to main
  demo/kserve/custom-manifests/caikit/caikit-standalone/caikit-standalone-isvc-grpc.yaml
  demo/kserve/custom-manifests/caikit/caikit-standalone/caikit-standalone-isvc.yaml
  demo/kserve/custom-manifests/caikit/caikit-standalone/caikit-standalone-servingruntime-grpc.yaml
  demo/kserve/custom-manifests/caikit/caikit-standalone/caikit-standalone-servingruntime.yaml
  demo/kserve/deploy-embeddings-scripts.md
  demo/kserve/deploy-embeddings.md
  demo/kserve/scripts/test/grpc-call-embeddings.sh
  demo/kserve/scripts/test/http-call-embeddings.sh
  poetry.lock
  pyproject.toml
Labels: approved, lgtm, ok-to-test

#334 Sync Main with Release for 2.12
  poetry.lock
Labels: approved, lgtm
